.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GRML-HWINFO 1 "April 22, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
grml-hwinfo \- collect hardware information
.SH SYNOPSIS
.B grml-hwinfo [-d] [-f]
.SH DESCRIPTION
This manual page documents briefly the
.B grml-hwinfo
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBgrml-hwinfo\fP is a program that collects information regarding hardware.
.SH OPTIONS
.B -d
Save collected data in a directory named "grml-hwinfo-TIMESTAMP".

.B -f
Save collected data in a tarball named "grml-hwinfo-TIMESTAMP.tar.bz2".
Specify both -d and -f, as -df, to get the directory and the tarball.
.SH RUNNING AS ROOT
Running this program as root will make it gather additional information.
This includes DMI, DDC, disk, partition tables and other data normally
only available to root.
.SH AUTHOR
grml-hwinfo was written by Michael Prokop <mika@grml.org>.
.PP
This manual page was written by Michael Prokop <mika@grml.org>,
for the Grml project (but may be used by others).
